spring:
  application:
    name: photoC

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jikaigg
    username: root
    password: yaojikai2
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
